Add support for invoice transaction currency
btcpayserver/btcpayserver-php-client pull request #29
Opened 2020-05-11 11:46 UTC by martinkrcho

Payment creation via API does not support the transaction currency at the moment. This pull request add the `paymentCurrencies` data attribute to the invoice data.

2020-05-22 05:50 UTC, Kukks requested changes
This library needs to be adjusted so that you can provide an array of enabled payment methods. 

You should also use `supportedTransactionCurrencies` since `paymentCurrencies` is not currently supported in BTCpay (PR to fix this at  https://github.com/btcpayserver/btcpayserver/pull/1589)

The format for `supportedTransactionCurrencies` is as following:
```json
"supportedTransactionCurrencies": {
  "BTC": { "enabled": true}
}
```

The values possible for BTCPay are as follow:
* onchain bitcoin based currency - `BTC`, `BTC_ONCHAIN`, or `BTC_BTCLIKE`
* lightning - `BTC_OFFCHAIN`, or `BTC_LIGHTNINGLIKE`
* monero - `XMR_MONEROLIKE`

`BTC` can be changed to any enabled crypto on your server. Liquid assets count as an onchain bitcoin currency so you can specify them with `USDT`

2020-05-22 05:50 UTC, Kukks commented on src/BTCPayServer/Client/Client.php
> +            'paymentCurrencies' => $invoice->setTransactionCurrency(),
isn't `setTransactionCurrency` only to set one currency? BTCPay supports selecting multiple one on invoice creation

2021-01-03 16:54 UTC, ndeet commented on src/BTCPayServer/Client/Client.php
> +            'paymentCurrencies' => $invoice->setTransactionCurrency(),
Two problems I see here:
1) data passed needs to be an array
2) it should be the get and not the set method `$invoice->getTransactionCurrency()` 

@Kukks as you mentioned in the comments these get+setTransactionCurrency() methods only allow us to set one specific currency at the time which should work but on the other hand we may want to align with the API parameter `paymentCurrencies` and do the following:
- add a new property (paymentCurrencies) that can hold multiple currency symbols as array to the `Invoice` class
- add new getter + setter methods 
- extend `Client` class like above but with the new getter method

I will open a new PR for this shortly and reference this PR

2021-01-04 06:46 UTC, Kukks commented
Superseded by #45

2021-01-04 06:46 UTC, closed without merging